version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./static/uploads:/app/static/uploads
      - ./database:/app/database
    environment:
      - SECRET_KEY=mewmewmew
    user: "1000:1000"
    working_dir: /app
    restart: unless-stopped